### PR TITLE
Added flexible parallel execution for the Folder Update.

### PR DESCRIPTION
**Pull request by Dinsmoor**
Effectively speeds up import (depending on folder contents and cpus available) by about 30%, mostly improves hashing time and some metadata collection operations that the filesystem can handle more of a load.

Sqlite3 object no longer checks for same thread. Default sqlite3 thread safety mode is serialization: it is not as fast as if postrgresql would be used but it is still thread safe for all operations. https://www.sqlite.org/threadsafe.html

Further improvements may be to create a processing job system to have ffmpeg and PIL processes work on file objects asynchronously, but it would increase the complexity substantially and not worth it at this time. Using cProfile may be wise in order to perform further performance enhancements.

### CODE REVIEW

**Comment by reasv** [comment]
I'm going to take a second look at this tomorrow before merging it, because I have to be sure that this doesn't change the behaviour of the file scanning code. It handles some truly absurd edge cases that might not be obvious from the code itself, so I am careful when changing it.

It doesn't seem like your commit touches on any of those things, though. From what I gather:

1. The order of files yielded by the function changes, any files that need to be hashed/processed are handled at the end
2. It now needs to keep a full list of all the files in memory before processing them. I had written this part using generators in order to avoid this, since the number of files is unbounded. Realistically, this is probably not an issue in practice, but it does mean memory usage increases linearly with the number of files. It's probably not enough to matter given the number of files that can be practically handled by panoptikon.

Is there a reason why you changed the behaviour here?
https://github.com/Dinsmoor/panoptikon/blob/performance/src/panoptikon/files.py#L195

**Comment by Dinsmoor** [comment]
could just be a refactoring artifact from me not 100% understanding every bit and piece. It "works on my machine" though :clown_face: 

I did notice that it failed to sanely handle corrupt .png files from a kdenlive project directory. Idk if it did that before my changes or not.

I'm still looking for a few places to improve performance. The ffmpeg -hwaccel auto change in the subprocess also helped a lot but it might be more performant to spawn multiple ffmpeg subprocesses if a gpu is avaliable - one (or more) of the cpu, and 2 (or more) on the gpu. With nvdec on my 4070super, I only reach maximum 24% utilization on 1080p60fps videos. Will have to figure out a smart way to do more utilization - maybe do it the KISS way and just spawn 5x of them on both cpu and gpu and setting the process nice level to 15 or something so it doesn't lock up someone's system.

Still working on this, but I'll look at that yield behavior.

**Comment by Dinsmoor** [comment]
Okay, I see that you were counting NoneType returns as a +1 to errors, and you want them all. Fixed.

**Comment by reasv** [comment]
What did it do with those corrupted pngs?

**Comment by Dinsmoor** [comment]
PIL threw a ValueError because the png header told panoptikon it had an x and y dimension of 0. Was exception handled and ignored, but traceback was provided to the user. Not a part of this PR though, would be better in its own issue.

**Comment by Dinsmoor** [comment]
This is actually slower by 20% in most cases. Maybe it seemed like it was faster because of this: https://github.com/reasv/panoptikon/pull/4/commits/7050814b52077254c1612ada97fa63ebef498329 and the original folder I was working with had a lot of videos.

Closing, but may retry later.

**Pull request closed without merging**
